/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BIAssignment;

import io.github.bonigarcia.wdm.WebDriverManager;

import java.io.File;
import java.io.IOException;
import java.time.Duration;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
//import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

public class App {

    public static ChromeDriver createDriver() {
        //Create a new chrome Driver and Return the same
        ChromeDriver driver;
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        return driver;
    }
//    public static FirefoxDriver createDriver() {
//        //Create a new Firefox Driver and Return the same
//        FirefoxDriver driver;
//        WebDriverManager.firefoxdriver().setup();
//        driver = new FirefoxDriver();
//        return driver;
//    }

//    public static void printQKartLoadingtime(FirefoxDriver driver)
public static void printQKartLoadingtime(ChromeDriver driver){
        //Navigate to home page of QKart and verify the time taken for the page to
        // load
        /* Initializing a StopWatch object */
        long s = System.currentTimeMillis();
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        // WebDriverWait wt = new WebDriverWait(driver,5);
        WebDriverWait wt = new WebDriverWait(driver, Duration.ofSeconds(5));
        wt.until(ExpectedConditions.elementToBeClickable(By.xpath("//button[text()='Login']")));
        long e = System.currentTimeMillis();
        long r = e - s;
        System.out.println("");
        System.out.println("Page load time in milliseconds: " + r);
        // driver.close();
    }

//    public static void captureFullPageScreenshot(FirefoxDriver driver) throws IOException
public static void captureFullPageScreenshot(ChromeDriver driver) throws IOException {
        //Capture the full page screenshot
        // Save the file with a unique name
        // Print the path of the file
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        // Thread.sleep(5000);
        String timestamp = String.valueOf(java.time.LocalDateTime.now());
        // System.out.println(timestamp);
        // String screenshotFileName = timestamp.toString().replace("","_");
        File ScreenshotFile = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        String toSavein = ".\\Screenshots\\";
        String fileName = "Screenshot_" + timestamp.toString().replace(":", "-") + ".png";
        System.out.println("");
        System.out.println("Full Page Screenshot captured and saved at : " + fileName);
        File destinationFile = new File(toSavein, fileName);
        FileUtils.copyFile(ScreenshotFile, destinationFile);
        // Thread.sleep(5000);
        // FileUtils.copyFile(ScreenshotFile, new
        // File("C:/Users/Hariharan/Desktop/BIAssignment/app/Screenshots//"+ timestamp
        // +".png"));
    }

//    public static void GetProductImageandURL(FirefoxDriver driver, String productName) throws InterruptedException
    public static void GetProductImageandURL(ChromeDriver driver, String productName) throws InterruptedException {
        //Given the product name, print the price of the project and the url of
        // the image
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        // productName = "Yonex";
        WebElement searchBox = driver.findElement(By.xpath("//input[@name='search'][1]"));
        searchBox.clear();
        searchBox.sendKeys(productName);
        Thread.sleep(5000);
        // identify image
        WebElement l = driver.findElement(By.xpath("//img[@class='MuiCardMedia-root MuiCardMedia-media MuiCardMedia-img css-rhsghg']"));
        // identify price
        WebElement price = driver.findElement(By.xpath("//p[@class='MuiTypography-root MuiTypography-body1 css-uickyz']"));
        System.out.println("");
        //getText() to get the price of the product
        System.out.println("Price of the product: " + price.getText());
        // getAttribute() to get src of image
        System.out.println("Url of the product image is: " + l.getAttribute("src"));
    }

    public static void main(String[] args) {
        ChromeDriver driver = createDriver();
//        FirefoxDriver driver = createDriver();
        String input = String.join(" ", args);
        try {

            printQKartLoadingtime(driver);

            captureFullPageScreenshot(driver);

            GetProductImageandURL(driver, input);

        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            driver.quit();
        }
    }
}
